import type { Product, Material, TimelineEvent, Certification, PassportData } from '../types';

// Static product data for IN2ME Digital Product Passport prototype

export const products: Product[] = [
  {
    id: '1',
    name: 'Detachable Skirt-Pants',
    name_es: 'Pantalón-Falda Desmontable',
    collection: 'NEWME',
    collection_es: 'NEWME',
    season: 'Pre-Fall 2026',
    sku: 'IN2ME-PF26-SKT-001',
    passport_id: 'PP-IN2ME-001-SKT',
    description: 'A full-circle maxi skirt in warm khaki Casimir, defined by two front zippers that reveal tailored pants beneath. The contrasting burgundy faille waistbands connects the piece to the collection recurring design signature.',
    description_es: 'Falda circular en Casimir caqui cálido, definida por dos cierres al frente que revelan los pantalones sastre debajo. Las pretina de faille burdeo conecta la pieza con la firma de diseño recurrente de la colección',
    hero_image_url: 'https://images.unsplash.com/photo-1509631179647-0177339150241?w=1260&h=750&fit=crop',
    back_image_url: null,
    detail_image_url: 'https://images.unsplash.com/photo-1594938298603-c914edb15853?w=1260&h=750&fit=crop',
    created_at: '2026-01-15',
  },
  {
    id: '2',
    name: 'Tailored Pants',
    name_es: 'Pantalones Sastre',
    collection: 'NEWME',
    collection_es: 'NEWME',
    season: 'Pre-Fall 2026',
    sku: 'IN2ME-PF26-TRS-001',
    passport_id: 'PP-IN2ME-002-TRS',
    description: 'Tailored trousers in warm khaki Casimir with a clean silhouette. The burgundy faya waistband anchors the design, while a welt back pocket and structured front fall deliver architectural precision.',
    description_es: 'Pantalón sastre en Casimir caqui cálido con una silueta limpia. La pretina de faya burdeos ancla el diseño, mientras que un bolsillo trasero y una caída estructurada al frente aportan precisión arquitectónica.',
    hero_image_url: 'https://images.unsplash.com/photo-1509631179647-0177339150241?w=1260&h=750&fit=crop',
    back_image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1260&h=750&fit=crop',
    detail_image_url: 'https://images.unsplash.com/photo-1594938298603-c914edb15853?w=1260&h=750&fit=crop',
    created_at: '2026-01-15',
  },
];

export const materials: Record<string, Material[]> = {
  '1': [
    {
      id: 'm1-1',
      product_id: '1',
      name: 'Casimir Blend',
      name_es: 'Casimir Mezclado',
      fabric_type: 'Woven suiting',
      fabric_type_es: 'Tejido sastre',
      origin_country: 'Chile',
      origin_region: 'Santiago Metropolitan Region',
      composition_descriptor: '50% Polyester, 30% Wool, 20% Viscose — A structured woven fabric with subtle texture and durability.',
      composition_descriptor_es: '50% Poliéster, 30% Lana, 20% Viscosa — Una tela tejida estructurada con textura sutil y durabilidad.',
      color: 'Khaki',
      certification: null,
      supplier_name: 'Textiles Independencia, Santiago',
      sort_order: 1,
    },
    {
      id: 'm1-2',
      product_id: '1',
      name: 'Faya',
      name_es: 'Faya',
      fabric_type: 'Grooved texture with horizontal ribs',
      fabric_type_es: 'Textura acanalada con nervaduras horizontales',
      origin_country: 'Chile',
      origin_region: 'Region Metropolitana',
      composition_descriptor: 'Subtle ribbed texture. With body. Waistband only.',
      composition_descriptor_es: 'Tejido con textura acanalada. Con cuerpo. Solo pretina.',
      color: 'Burgundy',
      certification: null,
      supplier_name: 'Textiles Independencia, Santiago',
      sort_order: 2,
    },
    {
      id: 'm1-3',
      product_id: '1',
      name: 'Metal Zipper Hardware',
      name_es: 'Herraje de Cierre Metálico',
      fabric_type: 'Accessory hardware',
      fabric_type_es: 'Herraje de accesorio',
      origin_country: 'Chile',
      origin_region: null,
      composition_descriptor: 'Silver-finish metal zippers, dual-ended for reversible styling options.',
      composition_descriptor_es: 'Cremalleras metálicas con acabado plata, de doble extremo para opciones de estilo reversible.',
      color: 'Silver',
      certification: null,
      supplier_name: 'Jesara, Santiago',
      sort_order: 3,
    },
  ],
  '2': [
    {
      id: 'm2-1',
      product_id: '2',
      name: 'Casimir Blend',
      name_es: 'Casimir Mezclado',
      fabric_type: 'Woven suiting',
      fabric_type_es: 'Tejido sastre',
      origin_country: 'Chile',
      origin_region: 'Santiago Metropolitan Region',
      composition_descriptor: '50% Polyester, 30% Wool, 20% Viscose — A structured woven fabric with subtle texture and durability.',
      composition_descriptor_es: '50% Poliéster, 30% Lana, 20% Viscosa — Una tela tejida estructurada con textura sutil y durabilidad.',
      color: 'Khaki',
      certification: null,
      supplier_name: 'Textiles Independencia, Santiago',
      sort_order: 1,
    },
    {
      id: 'm2-2',
      product_id: '2',
      name: 'Faya',
      name_es: 'Faya',
      fabric_type: 'Grooved texture with horizontal ribs',
      fabric_type_es: 'Textura acanalada con nervaduras horizontales',
      origin_country: 'Chile',
      origin_region: 'Region Metropolitana',
      composition_descriptor: 'Subtle ribbed texture. With body. Waistband only.',
      composition_descriptor_es: 'Tejido con textura acanalada. Con cuerpo. Solo pretina.',
      color: 'Burgundy',
      certification: null,
      supplier_name: 'Textiles Independencia, Santiago',
      sort_order: 2,
    },
  ],
};

export const timeline: Record<string, TimelineEvent[]> = {
  '1': [
    {
      id: 't1-1',
      product_id: '1',
      stage: 'Raw Material Sourcing',
      stage_es: 'Obtención de Materia Prima',
      location: 'Santiago',
      country: 'Chile',
      event_date: '2026-01-10',
      description: 'Fabrics sourced from regional suppliers within the Santiago Metropolitan Region. All materials selected for durability and structural integrity.',
      description_es: 'Telas obtenidas de proveedores regionales dentro de la Región Metropolitana de Santiago. Todos los materiales seleccionados por durabilidad e integridad estructural.',
      verified: true,
      sort_order: 1,
    },
    {
      id: 't1-2',
      product_id: '1',
      stage: 'Dyeing & Finishing',
      stage_es: 'Teñido y Acabado',
      location: 'Valparaíso',
      country: 'Chile',
      event_date: '2026-01-15',
      description: 'Fabric dyeing completed at a specialized facility in Valparaíso using low-impact process methods.',
      description_es: 'Teñido de tela completado en una instalación especializada en Valparaíso utilizando métodos de bajo impacto.',
      verified: true,
      sort_order: 2,
    },
    {
      id: 't1-3',
      product_id: '1',
      stage: 'Pattern Design',
      stage_es: 'Diseño de Patrones',
      location: 'Santiago',
      country: 'Chile',
      event_date: '2026-01-20',
      description: 'Pattern development at the IN2ME atelier. Genderless pattern cut for flexibility of form across body types.',
      description_es: 'Desarrollo de patrones en el atelier IN2ME. Patrón sin género cortado para flexibilidad de forma en diferentes tipos de cuerpo.',
      verified: true,
      sort_order: 3,
    },
    {
      id: 't1-4',
      product_id: '1',
      stage: 'Assembly & Sewing',
      stage_es: 'Ensamble y Costura',
      location: 'Santiago',
      country: 'Chile',
      event_date: '2026-01-25',
      description: 'Hand assembly and sewing by skilled artisans at the IN2ME atelier. Reinforced construction.',
      description_es: 'Ensamble y costura a mano por artesanos calificados en el atelier IN2ME. Construcción reforzada.',
      verified: true,
      sort_order: 4,
    },
    {
      id: 't1-5',
      product_id: '1',
      stage: 'Hardware Installation',
      stage_es: 'Instalación de Herrajes',
      location: 'Santiago',
      country: 'Chile',
      event_date: '2026-01-28',
      description: 'Metal zipper hardware fitted and tested for mechanical reliability. Dual-ended zippers allow reversible styling.',
      description_es: 'Herraje de cierre metálico instalado y probado para confiabilidad mecánica. Cremalleras de doble extremo permiten estilo reversible.',
      verified: true,
      sort_order: 5,
    },
    {
      id: 't1-6',
      product_id: '1',
      stage: 'Quality Control',
      stage_es: 'Control de Calidad',
      location: 'Santiago',
      country: 'Chile',
      event_date: '2026-02-01',
      description: 'Final quality review at the atelier. Each piece inspected for construction integrity, hardware function, and finish consistency.',
      description_es: 'Revisión final de calidad en el atelier. Cada pieza inspeccionada por integridad de construcción, funcionamiento de herraje y consistencia de acabado.',
      verified: true,
      sort_order: 6,
    },
  ],
  '2': [
    {
      id: 't2-1',
      product_id: '2',
      stage: 'Raw Material Sourcing',
      stage_es: 'Obtención de Materia Prima',
      location: 'Santiago',
      country: 'Chile',
      event_date: '2026-01-10',
      description: 'Fabrics sourced from regional suppliers within the Santiago Metropolitan Region. All materials selected for durability and structural integrity.',
      description_es: 'Telas obtenidas de proveedores regionales dentro de la Región Metropolitana de Santiago. Todos los materiales seleccionados por durabilidad e integridad estructural.',
      verified: true,
      sort_order: 1,
    },
    {
      id: 't2-2',
      product_id: '2',
      stage: 'Pattern Design',
      stage_es: 'Diseño de Patrones',
      location: 'Santiago',
      country: 'Chile',
      event_date: '2026-01-18',
      description: 'Pattern development at the IN2ME atelier. Genderless pattern designed for architectural volume and functional fit.',
      description_es: 'Desarrollo de patrones en el atelier IN2ME. Patrón sin género diseñado para volumen arquitectónico y ajuste funcional.',
      verified: true,
      sort_order: 2,
    },
    {
      id: 't2-3',
      product_id: '2',
      stage: 'Assembly & Sewing',
      stage_es: 'Ensamble y Costura',
      location: 'Santiago',
      country: 'Chile',
      event_date: '2026-01-24',
      description: 'Assembly and sewing by skilled artisans. Reinforced waistband construction with metal hardware integration.',
      description_es: 'Ensamble y costura por artesanos calificados. Construcción de pretina reforzada con integración de herraje metálico.',
      verified: true,
      sort_order: 3,
    },
    {
      id: 't2-4',
      product_id: '2',
      stage: 'Quality Control',
      stage_es: 'Control de Calidad',
      location: 'Santiago',
      country: 'Chile',
      event_date: '2026-01-30',
      description: 'Final quality review at the atelier. Each piece inspected for construction integrity, hardware function, and finish consistency.',
      description_es: 'Revisión final de calidad en el atelier. Cada pieza inspeccionada por integridad de construcción, funcionamiento de herraje y consistencia de acabado.',
      verified: true,
      sort_order: 4,
    },
  ],
};

export const certifications: Record<string, Certification[]> = {
  '1': [],
  '2': [],
};

export function getPassportData(product: Product): PassportData {
  return {
    product,
    materials: materials[product.id] || [],
    timeline: timeline[product.id] || [],
    certifications: certifications[product.id] || [],
  };
}

export { products as staticProducts };
